[project]
name = "polyproj"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ottokar Callewaert", email = "ottokar.callewaert@apixa.com" },
]
requires-python = ">=3.10"
dependencies = ["numpy>=2.2.6", "pyopencl>=2025.1"]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = ["matplotlib>=3.10.3", "pytest>=8.4.0"]
benchmark = [
    "pytest-benchmark>=4.0.0",
    "psutil>=5.9.0",
    "memory-profiler>=0.61.0",
    "matplotlib>=3.10.3",
]
